//
//  PostListInteractor.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostListInteractor {
}

// MARK: - Extensions -

extension PostListInteractor: PostListInteractorInterface {
}
