//
//  PostListInterfaces.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PostListWireframeInterface: WireframeInterface {
}

protocol PostListViewInterface: ViewInterface {
}

protocol PostListPresenterInterface: PresenterInterface {
}

protocol PostListInteractorInterface: InteractorInterface {
}
