//
//  PostListPresenter.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostListPresenter {

    // MARK: - Private properties -

    private unowned let view: PostListViewInterface
    private let interactor: PostListInteractorInterface
    private let wireframe: PostListWireframeInterface

    // MARK: - Lifecycle -

    init(view: PostListViewInterface, interactor: PostListInteractorInterface, wireframe: PostListWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PostListPresenter: PostListPresenterInterface {
}
