//
//  PostLDetailViewController.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostLDetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: PostLDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
    }

}

// MARK: - Extensions -

extension PostLDetailViewController: PostLDetailViewInterface {
}
