//
//  PostLDetailWireframe.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostLDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = PostLDetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = PostLDetailInteractor()
        let presenter = PostLDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PostLDetailWireframe: PostLDetailWireframeInterface {
}
