//
//  PostLDetailPresenter.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostLDetailPresenter {

    // MARK: - Private properties -

    private unowned let view: PostLDetailViewInterface
    private let interactor: PostLDetailInteractorInterface
    private let wireframe: PostLDetailWireframeInterface

    // MARK: - Lifecycle -

    init(view: PostLDetailViewInterface, interactor: PostLDetailInteractorInterface, wireframe: PostLDetailWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PostLDetailPresenter: PostLDetailPresenterInterface {
}
