//
//  PostLDetailInterfaces.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PostLDetailWireframeInterface: WireframeInterface {
}

protocol PostLDetailViewInterface: ViewInterface {
}

protocol PostLDetailPresenterInterface: PresenterInterface {
}

protocol PostLDetailInteractorInterface: InteractorInterface {
}
