//
//  PostLDetailInteractor.swift
//  RedditDemo
//
//  Created by Santiago Apaza on 6/7/20.
//  Copyright (c) 2020 Ayllu. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostLDetailInteractor {
}

// MARK: - Extensions -

extension PostLDetailInteractor: PostLDetailInteractorInterface {
}
